### PR TITLE
Fix for a couple of errors I've found during first setup

### PR DESCRIPTION
**Pull request by acydh**
The variable name change fixes the following error on npm start:

AssertionError [ERR_ASSERTION]: You should configure either ELASTIC_CLOUD_ID or ELASTIC_ADDRESS

___

The module import change fixes the following error on npm start:

SyntaxError: The requested module 'readable-stream' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
Thanks for the fix!!

Which version of Node.js are you using?
I'm not having any issue with `readable-stream`.

**Comment by acydh** [comment]
No worries :) 
Node v12.18.3

**Comment by mcollina** [comment]
You need to use the latest v12, e.g. >= v12.20.x. named exports for CJS modules landed there.

**Comment by delvedor** [comment]
What @mcollina said :)
Can you remove the import change? So I can merge the other fixes!

**Comment by mcollina** [comment]
There is no need to change the import fix. Just update the minimum version of Node.js inside the package.json.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by acydh** [comment]
thanks :)

**Review by chrismilleruk — CHANGES_REQUESTED** [review]
The copy mentions `ELASTIC_URL` here so should also be changed to `ELASTIC_ADDRESS`

**Comment by chrismilleruk** [comment]
This PR should fix issue #6 also.

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
